spring:
  application:
    name: FINANCE-TRACKER

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Sql@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true

