spring:
  application:
    name: FINANCE-TRACKER
  datasource:
    url: jdbc:mysql://localhost:3306/finance_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Sql@123
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
  security:
    enabled: false

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari: DEBUG